# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{opensrs}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Delsman"]
  s.date = %q{2011-01-28}
  s.description = %q{Provides support to utilise the OpenSRS API with Ruby/Rails.}
  s.email = %q{josh@voxx.it}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/opensrs.rb",
    "lib/opensrs/response.rb",
    "lib/opensrs/server.rb",
    "lib/opensrs/xml.rb",
    "spec/opensrs/xml_spec.rb",
    "spec/spec_helper.rb",
    "test/opensrs_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/voxxit/opensrs}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Provides support to utilise the OpenSRS API with Ruby/Rails.}
  s.test_files = [
    "spec/opensrs/xml_spec.rb",
    "spec/spec_helper.rb",
    "test/opensrs_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<libxml-ruby>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<libxml-ruby>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

