# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "opensrs"
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Delsman"]
  s.date = "2013-04-04"
  s.description = "Provides support to utilize the OpenSRS API with Ruby/Rails."
  s.email = "jdelsman@voxxit.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/opensrs.rb",
    "lib/opensrs/response.rb",
    "lib/opensrs/server.rb",
    "lib/opensrs/version.rb",
    "lib/opensrs/xml_processor.rb",
    "lib/opensrs/xml_processor/libxml.rb",
    "lib/opensrs/xml_processor/nokogiri.rb",
    "opensrs.gemspec",
    "spec/opensrs/server_spec.rb",
    "spec/opensrs/version_spec.rb",
    "spec/opensrs/xml_processor/libxml_spec.rb",
    "spec/opensrs/xml_processor/nokogiri_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/voxxit/opensrs"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Provides support to utilize the OpenSRS API with Ruby/Rails."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<libxml-ruby>, ["~> 2.6.0"])
      s.add_development_dependency(%q<nokogiri>, ["~> 1.6.1"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<git>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<libxml-ruby>, ["~> 2.6.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.6.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<libxml-ruby>, ["~> 2.6.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.6.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

