name: Ruby

on: push

jobs:
  test:
    name: "Rspec (on Ruby ${{ matrix.ruby_version }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.5, 2.6, 2.7, 3.0, 3.1]

    steps:
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Run Rspec
      run: bundle exec rspec spec
